/*++

Module Name:

    public.h

Abstract:

    Shared protocol declarations for the Xdows Security driver bridge.

Environment:

    User and kernel mode.

--*/

#pragma once

#define XDOWS_SECURITY_PROTOCOL_VERSION 6u
#define XDOWS_SECURITY_DRIVER_BUILD_ID 2026072801ULL
#define XDOWS_SECURITY_EVENT_TYPE_COUNT 9u
#define XDOWS_SECURITY_CAP_PRIORITY_QUEUE 0x00000001u
#define XDOWS_SECURITY_CAP_DIRTY_WRITE_COALESCING 0x00000002u
#define XDOWS_SECURITY_CAP_BUILD_ID 0x00000004u
#define XDOWS_SECURITY_CAP_STARTUP_SELF_PROTECT 0x00000008u
#define XDOWS_SECURITY_CAP_USER_DECISION_HOLD 0x00000010u
#define XDOWS_SECURITY_CAP_PROCESS_MANAGEMENT 0x00000020u
#define XDOWS_SECURITY_CAP_ENHANCED_SELF_PROTECT 0x00000040u
#define XDOWS_SECURITY_CAPABILITIES ( \
    XDOWS_SECURITY_CAP_PRIORITY_QUEUE | \
    XDOWS_SECURITY_CAP_DIRTY_WRITE_COALESCING | \
    XDOWS_SECURITY_CAP_BUILD_ID | \
    XDOWS_SECURITY_CAP_STARTUP_SELF_PROTECT | \
    XDOWS_SECURITY_CAP_USER_DECISION_HOLD | \
    XDOWS_SECURITY_CAP_PROCESS_MANAGEMENT | \
    XDOWS_SECURITY_CAP_ENHANCED_SELF_PROTECT)
#define XDOWS_SECURITY_MODULE_TOKEN_AUTH 0x00000001u
#define XDOWS_SECURITY_MODULE_PROCESS 0x00000002u
#define XDOWS_SECURITY_MODULE_FILE 0x00000004u
#define XDOWS_SECURITY_MODULE_INJECTION 0x00000008u
#define XDOWS_SECURITY_MODULE_SELF_PROTECT 0x00000010u
#define XDOWS_SECURITY_REQUIRED_MODULES ( \
    XDOWS_SECURITY_MODULE_TOKEN_AUTH | \
    XDOWS_SECURITY_MODULE_PROCESS | \
    XDOWS_SECURITY_MODULE_FILE | \
    XDOWS_SECURITY_MODULE_INJECTION | \
    XDOWS_SECURITY_MODULE_SELF_PROTECT)
#define XDOWS_SECURITY_MAX_PATH_CHARS 520u
#define XDOWS_SECURITY_MAX_COMMAND_CHARS 1024u
#define XDOWS_SECURITY_MAX_REASON_CHARS 128u
#define XDOWS_SECURITY_TOKEN_CHARS 64u
#define XDOWS_SECURITY_MAX_LOG_MODULE_CHARS 32u
#define XDOWS_SECURITY_MAX_LOG_MESSAGE_CHARS 256u
#define XDOWS_SECURITY_MAX_PROCESS_NAME_CHARS 260u
#define XDOWS_SECURITY_PROCESS_BATCH_SIZE 64u

#define XDOWS_SECURITY_DEVICE_NAME L"\\Device\\XdowsSecurityDriver"
#define XDOWS_SECURITY_SYMBOLIC_NAME L"\\DosDevices\\Global\\XdowsSecurityDriver"
#define XDOWS_SECURITY_LEGACY_SYMBOLIC_NAME L"\\DosDevices\\XdowsSecurityDriver"
#define XDOWS_SECURITY_USER_DEVICE_PATH L"\\\\.\\XdowsSecurityDriver"

#define FILE_DEVICE_XDOWS_SECURITY 0x8000u

#define IOCTL_XDOWS_SECURITY_REGISTER_CLIENT \
    CTL_CODE(FILE_DEVICE_XDOWS_SECURITY, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_XDOWS_SECURITY_HEARTBEAT \
    CTL_CODE(FILE_DEVICE_XDOWS_SECURITY, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_XDOWS_SECURITY_GET_NEXT_EVENT \
    CTL_CODE(FILE_DEVICE_XDOWS_SECURITY, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_XDOWS_SECURITY_SUBMIT_DECISION \
    CTL_CODE(FILE_DEVICE_XDOWS_SECURITY, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_XDOWS_SECURITY_GET_STATE \
    CTL_CODE(FILE_DEVICE_XDOWS_SECURITY, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_XDOWS_SECURITY_DISCONNECT_CLIENT \
    CTL_CODE(FILE_DEVICE_XDOWS_SECURITY, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_XDOWS_SECURITY_REGISTER_PROTECTED_PROCESS \
    CTL_CODE(FILE_DEVICE_XDOWS_SECURITY, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_XDOWS_SECURITY_SET_VOLUNTARY_EXIT \
    CTL_CODE(FILE_DEVICE_XDOWS_SECURITY, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_XDOWS_SECURITY_AUTHORIZED_SHUTDOWN \
    CTL_CODE(FILE_DEVICE_XDOWS_SECURITY, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_XDOWS_SECURITY_GET_NEXT_LOG \
    CTL_CODE(FILE_DEVICE_XDOWS_SECURITY, 0x80A, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_XDOWS_SECURITY_SET_STARTUP_PROTECTION \
    CTL_CODE(FILE_DEVICE_XDOWS_SECURITY, 0x80B, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_XDOWS_SECURITY_QUERY_PROCESSES \
    CTL_CODE(FILE_DEVICE_XDOWS_SECURITY, 0x80C, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_XDOWS_SECURITY_OPERATE_PROCESS \
    CTL_CODE(FILE_DEVICE_XDOWS_SECURITY, 0x80D, METHOD_BUFFERED, FILE_ANY_ACCESS)

DEFINE_GUID(GUID_DEVINTERFACE_XdowsSecurityDriver,
    0xec5db072, 0x8119, 0x4d65, 0xa7, 0xae, 0x67, 0xd7, 0xf3, 0x10, 0x05, 0xe1);
// {ec5db072-8119-4d65-a7ae-67d7f31005e1}

typedef enum _XDOWS_SECURITY_EVENT_TYPE {
    XdowsSecurityEventNone = 0,
    XdowsSecurityEventProcessCreate = 1,
    XdowsSecurityEventFileCreate = 2,
    XdowsSecurityEventFileWrite = 3,
    XdowsSecurityEventFileRename = 4,
    XdowsSecurityEventProcessHandle = 5,
    XdowsSecurityEventThreadHandle = 6,
    XdowsSecurityEventImageLoad = 7,
    XdowsSecurityEventDriverLog = 8
} XDOWS_SECURITY_EVENT_TYPE;

typedef enum _XDOWS_SECURITY_DECISION_TYPE {
    XdowsSecurityDecisionUnknown = 0,
    XdowsSecurityDecisionAllow = 1,
    XdowsSecurityDecisionBlock = 2,
    XdowsSecurityDecisionTimeout = 3,
    XdowsSecurityDecisionPending = 4
} XDOWS_SECURITY_DECISION_TYPE;

typedef enum _XDOWS_SECURITY_MODEL_MODE {
    XdowsSecurityModelStandard = 0,
    XdowsSecurityModelFlash = 1,
    XdowsSecurityModelPro = 2,
    XdowsSecurityModelAdaptive = 3
} XDOWS_SECURITY_MODEL_MODE;

typedef enum _XDOWS_SECURITY_EVENT_FLAGS {
    XdowsSecurityEventFlagNone = 0x00000000u,
    XdowsSecurityEventFlagFileOpenNameAvailable = 0x00000001u,
    XdowsSecurityEventFlagUserModeRequired = 0x00000002u,
    XdowsSecurityEventFlagThreatConfirmed = 0x00000004u
} XDOWS_SECURITY_EVENT_FLAGS;

typedef enum _XDOWS_SECURITY_LOG_SEVERITY {
    XdowsSecurityLogDebug = 0,
    XdowsSecurityLogInfo = 1,
    XdowsSecurityLogWarning = 2,
    XdowsSecurityLogError = 3,
    XdowsSecurityLogFatal = 4
} XDOWS_SECURITY_LOG_SEVERITY;

typedef enum _XDOWS_SECURITY_PROCESS_OPERATION {
    XdowsSecurityProcessOperationNone = 0,
    XdowsSecurityProcessOperationSuspend = 1,
    XdowsSecurityProcessOperationResume = 2,
    XdowsSecurityProcessOperationTerminate = 3
} XDOWS_SECURITY_PROCESS_OPERATION;

typedef struct _XDOWS_SECURITY_PROTOCOL_HEADER {
    ULONG Size;
    ULONG Version;
} XDOWS_SECURITY_PROTOCOL_HEADER, *PXDOWS_SECURITY_PROTOCOL_HEADER;

typedef struct _XDOWS_SECURITY_REGISTER_REQUEST {
    XDOWS_SECURITY_PROTOCOL_HEADER Header;
    ULONG ClientProcessId;
    ULONG Flags;
    ULONG HeartbeatTimeoutMs;
    ULONG Reserved;
} XDOWS_SECURITY_REGISTER_REQUEST, *PXDOWS_SECURITY_REGISTER_REQUEST;

typedef struct _XDOWS_SECURITY_REGISTER_RESPONSE {
    XDOWS_SECURITY_PROTOCOL_HEADER Header;
    ULONG Status;
    ULONG ProtocolVersion;
    ULONG DefaultKernelWaitTimeoutMs;
    ULONG Capabilities;
    ULONGLONG DriverBuildId;
    WCHAR ShutdownToken[XDOWS_SECURITY_TOKEN_CHARS + 1];
} XDOWS_SECURITY_REGISTER_RESPONSE, *PXDOWS_SECURITY_REGISTER_RESPONSE;

typedef struct _XDOWS_SECURITY_HEARTBEAT_REQUEST {
    XDOWS_SECURITY_PROTOCOL_HEADER Header;
    ULONG ClientProcessId;
    ULONG Reserved;
} XDOWS_SECURITY_HEARTBEAT_REQUEST, *PXDOWS_SECURITY_HEARTBEAT_REQUEST;

typedef struct _XDOWS_SECURITY_EVENT {
    XDOWS_SECURITY_PROTOCOL_HEADER Header;
    ULONGLONG EventId;
    ULONGLONG CorrelationId;
    ULONG EventType;
    ULONG Flags;
    ULONG ProcessId;
    ULONG ParentProcessId;
    ULONG CreatingProcessId;
    ULONG CreatingThreadId;
    ULONG KernelWaitTimeoutMs;
    ULONG Reserved;
    WCHAR ImagePath[XDOWS_SECURITY_MAX_PATH_CHARS];
    WCHAR ActorImagePath[XDOWS_SECURITY_MAX_PATH_CHARS];
    WCHAR CommandLine[XDOWS_SECURITY_MAX_COMMAND_CHARS];
} XDOWS_SECURITY_EVENT, *PXDOWS_SECURITY_EVENT;

typedef struct _XDOWS_SECURITY_DECISION {
    XDOWS_SECURITY_PROTOCOL_HEADER Header;
    ULONGLONG EventId;
    ULONG Decision;
    ULONG CacheTtlMs;
    ULONG ResultCode;
    ULONG Reserved;
    WCHAR Reason[XDOWS_SECURITY_MAX_REASON_CHARS];
} XDOWS_SECURITY_DECISION, *PXDOWS_SECURITY_DECISION;

typedef struct _XDOWS_SECURITY_STATE {
    XDOWS_SECURITY_PROTOCOL_HEADER Header;
    ULONG ClientConnected;
    ULONG PendingEventCount;
    ULONG DroppedEventCount;
    ULONG ProcessProtectionEnabled;
    ULONG FileProtectionEnabled;
    ULONG SelfProtectionEnabled;
    ULONG ProtectedProcessId;
    ULONG StartupProtectionEnabled;
    ULONG ActiveModules;
    ULONG ProtocolVersion;
    ULONG Capabilities;
    ULONGLONG DriverBuildId;
    ULONG ReceivedByType[XDOWS_SECURITY_EVENT_TYPE_COUNT];
    ULONG DroppedByType[XDOWS_SECURITY_EVENT_TYPE_COUNT];
    ULONG TimedOutByType[XDOWS_SECURITY_EVENT_TYPE_COUNT];
} XDOWS_SECURITY_STATE, *PXDOWS_SECURITY_STATE;

typedef struct _XDOWS_SECURITY_PROTECTED_PROCESS_REQUEST {
    XDOWS_SECURITY_PROTOCOL_HEADER Header;
    ULONG ProcessId;
    ULONG MainThreadId;
    ULONG Flags;
    ULONG Reserved;
} XDOWS_SECURITY_PROTECTED_PROCESS_REQUEST, *PXDOWS_SECURITY_PROTECTED_PROCESS_REQUEST;

typedef struct _XDOWS_SECURITY_VOLUNTARY_EXIT_REQUEST {
    XDOWS_SECURITY_PROTOCOL_HEADER Header;
    ULONG ProcessId;
    ULONG IsVoluntaryExit;
    ULONG Reserved;
} XDOWS_SECURITY_VOLUNTARY_EXIT_REQUEST, *PXDOWS_SECURITY_VOLUNTARY_EXIT_REQUEST;

typedef struct _XDOWS_SECURITY_SHUTDOWN_REQUEST {
    XDOWS_SECURITY_PROTOCOL_HEADER Header;
    ULONG Flags;
    ULONG Reserved;
    WCHAR ShutdownToken[XDOWS_SECURITY_TOKEN_CHARS + 1];
} XDOWS_SECURITY_SHUTDOWN_REQUEST, *PXDOWS_SECURITY_SHUTDOWN_REQUEST;

typedef struct _XDOWS_SECURITY_STARTUP_PROTECTION_REQUEST {
    XDOWS_SECURITY_PROTOCOL_HEADER Header;
    ULONG ProcessId;
    ULONG Enabled;
    ULONG Reserved;
} XDOWS_SECURITY_STARTUP_PROTECTION_REQUEST, *PXDOWS_SECURITY_STARTUP_PROTECTION_REQUEST;

typedef struct _XDOWS_SECURITY_PROCESS_QUERY_REQUEST {
    XDOWS_SECURITY_PROTOCOL_HEADER Header;
    ULONG Cursor;
    ULONG Reserved;
    WCHAR AuthorizationToken[XDOWS_SECURITY_TOKEN_CHARS + 1];
} XDOWS_SECURITY_PROCESS_QUERY_REQUEST, *PXDOWS_SECURITY_PROCESS_QUERY_REQUEST;

typedef struct _XDOWS_SECURITY_PROCESS_ENTRY {
    ULONG ProcessId;
    ULONG ParentProcessId;
    ULONG SessionId;
    ULONG ThreadCount;
    ULONG HandleCount;
    ULONG BasePriority;
    ULONGLONG WorkingSetBytes;
    ULONGLONG PrivateBytes;
    WCHAR ImageName[XDOWS_SECURITY_MAX_PROCESS_NAME_CHARS];
} XDOWS_SECURITY_PROCESS_ENTRY, *PXDOWS_SECURITY_PROCESS_ENTRY;

typedef struct _XDOWS_SECURITY_PROCESS_QUERY_RESPONSE {
    XDOWS_SECURITY_PROTOCOL_HEADER Header;
    ULONG Count;
    ULONG NextCursor;
    ULONG HasMore;
    ULONG Reserved;
    XDOWS_SECURITY_PROCESS_ENTRY Entries[XDOWS_SECURITY_PROCESS_BATCH_SIZE];
} XDOWS_SECURITY_PROCESS_QUERY_RESPONSE, *PXDOWS_SECURITY_PROCESS_QUERY_RESPONSE;

typedef struct _XDOWS_SECURITY_PROCESS_OPERATION_REQUEST {
    XDOWS_SECURITY_PROTOCOL_HEADER Header;
    ULONG ProcessId;
    ULONG Operation;
    WCHAR AuthorizationToken[XDOWS_SECURITY_TOKEN_CHARS + 1];
} XDOWS_SECURITY_PROCESS_OPERATION_REQUEST, *PXDOWS_SECURITY_PROCESS_OPERATION_REQUEST;

typedef struct _XDOWS_SECURITY_LOG_ENTRY {
    XDOWS_SECURITY_PROTOCOL_HEADER Header;
    ULONGLONG EventId;
    ULONGLONG CorrelationId;
    ULONG Severity;
    ULONG DroppedCount;
    LARGE_INTEGER Timestamp;
    WCHAR Module[XDOWS_SECURITY_MAX_LOG_MODULE_CHARS];
    WCHAR Message[XDOWS_SECURITY_MAX_LOG_MESSAGE_CHARS];
} XDOWS_SECURITY_LOG_ENTRY, *PXDOWS_SECURITY_LOG_ENTRY;
