#pragma once

#define XDOWS_BOOT_PROTOCOL_VERSION 1u
#define XDOWS_BOOT_DRIVER_BUILD_ID 2026072901ULL
#define XDOWS_BOOT_MAX_RANGES 8u
#define XDOWS_BOOT_MAX_REQUEST_BYTES (1u * 1024u * 1024u)
#define XDOWS_BOOT_MAX_PENDING_BYTES (8u * 1024u * 1024u)
#define XDOWS_BOOT_MAX_PENDING_REQUESTS 128u
#define XDOWS_BOOT_DECISION_TIMEOUT_MS 25000u

#define XDOWS_BOOT_DEVICE_NAME L"\\Device\\XdowsSecurityBootFilter"
#define XDOWS_BOOT_SYMBOLIC_NAME L"\\DosDevices\\Global\\XdowsSecurityBootFilter"
#define XDOWS_BOOT_USER_DEVICE_PATH L"\\\\.\\XdowsSecurityBootFilter"

#define FILE_DEVICE_XDOWS_BOOT 0x8001u

#define IOCTL_XDOWS_BOOT_REGISTER_CLIENT \
    CTL_CODE(FILE_DEVICE_XDOWS_BOOT, 0x901, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_XDOWS_BOOT_CONFIGURE \
    CTL_CODE(FILE_DEVICE_XDOWS_BOOT, 0x902, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_XDOWS_BOOT_GET_NEXT_EVENT \
    CTL_CODE(FILE_DEVICE_XDOWS_BOOT, 0x903, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_XDOWS_BOOT_SUBMIT_DECISION \
    CTL_CODE(FILE_DEVICE_XDOWS_BOOT, 0x904, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_XDOWS_BOOT_GET_STATE \
    CTL_CODE(FILE_DEVICE_XDOWS_BOOT, 0x905, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

typedef enum _XDOWS_BOOT_DECISION_TYPE {
    XdowsBootDecisionUnknown = 0,
    XdowsBootDecisionAllow = 1,
    XdowsBootDecisionBlock = 2
} XDOWS_BOOT_DECISION_TYPE;

typedef struct _XDOWS_BOOT_PROTOCOL_HEADER {
    ULONG Size;
    ULONG Version;
} XDOWS_BOOT_PROTOCOL_HEADER, *PXDOWS_BOOT_PROTOCOL_HEADER;

typedef struct _XDOWS_BOOT_REGISTER_REQUEST {
    XDOWS_BOOT_PROTOCOL_HEADER Header;
    ULONG ClientProcessId;
    ULONG Reserved;
} XDOWS_BOOT_REGISTER_REQUEST, *PXDOWS_BOOT_REGISTER_REQUEST;

typedef struct _XDOWS_BOOT_REGISTER_RESPONSE {
    XDOWS_BOOT_PROTOCOL_HEADER Header;
    ULONG ProtocolVersion;
    ULONG MaxRequestBytes;
    ULONG MaxPendingBytes;
    ULONG DecisionTimeoutMs;
    ULONGLONG DriverBuildId;
} XDOWS_BOOT_REGISTER_RESPONSE, *PXDOWS_BOOT_REGISTER_RESPONSE;

typedef struct _XDOWS_BOOT_RAW_RANGE {
    LONGLONG Offset;
    ULONGLONG Length;
} XDOWS_BOOT_RAW_RANGE, *PXDOWS_BOOT_RAW_RANGE;

typedef struct _XDOWS_BOOT_CONFIGURE_REQUEST {
    XDOWS_BOOT_PROTOCOL_HEADER Header;
    ULONG DiskNumber;
    ULONG RangeCount;
    XDOWS_BOOT_RAW_RANGE Ranges[XDOWS_BOOT_MAX_RANGES];
} XDOWS_BOOT_CONFIGURE_REQUEST, *PXDOWS_BOOT_CONFIGURE_REQUEST;

typedef struct _XDOWS_BOOT_WRITE_EVENT {
    XDOWS_BOOT_PROTOCOL_HEADER Header;
    ULONGLONG EventId;
    ULONG DiskNumber;
    ULONG ProcessId;
    LONGLONG Offset;
    ULONG Length;
    ULONG Reserved;
} XDOWS_BOOT_WRITE_EVENT, *PXDOWS_BOOT_WRITE_EVENT;

typedef struct _XDOWS_BOOT_DECISION {
    XDOWS_BOOT_PROTOCOL_HEADER Header;
    ULONGLONG EventId;
    ULONG Decision;
    ULONG Reserved;
} XDOWS_BOOT_DECISION, *PXDOWS_BOOT_DECISION;

typedef struct _XDOWS_BOOT_STATE {
    XDOWS_BOOT_PROTOCOL_HEADER Header;
    ULONG ClientConnected;
    ULONG Configured;
    ULONG Attached;
    ULONG DiskNumber;
    ULONG PendingRequestCount;
    ULONG PendingBytes;
    ULONG BlockedNoClientCount;
    ULONG BlockedResourceCount;
    ULONG TimedOutCount;
    ULONG Reserved;
    ULONGLONG DriverBuildId;
} XDOWS_BOOT_STATE, *PXDOWS_BOOT_STATE;
